# -*- coding: utf-8 -*-
"""Importing  flat files.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zcdj03RP2b0u4ktjIi-0AjNV0kKyq38E
"""

from google.colab import files
uploaded = files.upload()

# Import package
import pandas as pd

titanicpandas = pd.read_csv('titanic.txt')

#consult first 10 rows of my file
titanicpandas.head(10)

#Understanding the dimensions of my dataset (rows and columns/ instances and atributes if you prefer)

titanicpandas.shape

#taking a deeper look 
titanicpandas.info()

# how many null vaules do I have?

titanicpandas.isnull().sum()

titanicpandas['PassengerId'].nunique()